fix: husky config

diff --git a/.husky/pre-commit b/.husky/pre-commit
--- a/.husky/pre-commit
+++ b/.husky/pre-commit
@@ -1,1 +1,31 @@
 pnpm lint-staged
+
+if [ -f .env ]; then
+  echo "❌ ERROR: You are trying to commit a .env file!"
+  echo "Please run 'git rm --cached .env' and add it to .gitignore."
+  exit 1
+fi
+
+if [ -f .env.dev ]; then
+  echo "❌ ERROR: You are trying to commit a .env.dev file!"
+  echo "Please run 'git rm --cached .env.dev' and add it to .gitignore."
+  exit 1
+fi
+
+if [ -f .env.prod ]; then
+  echo "❌ ERROR: You are trying to commit a .env.prod file!"
+  echo "Please run 'git rm --cached .env.prod' and add it to .gitignore."
+  exit 1
+fi
+
+if [ -f apps/mobile/google-services.json ]; then
+  echo "❌ ERROR: You are trying to commit a google-services.json file!"
+  echo "Please run 'git rm --cached google-services.json' and add it to .gitignore."
+  exit 1
+fi
+
+if [ -f apps/mobile/GoogleService-Info.plist ]; then
+  echo "❌ ERROR: You are trying to commit a GoogleService-Info.plist file!"
+  echo "Please run 'git rm --cached GoogleService-Info.plist' and add it to .gitignore."
+  exit 1
+fi
